baseURL = "https://cshung.github.io/"
languageCode = "en-us"
title = "My Blog"
theme = "exampleTheme"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 2